### ISSUE TITLE
Apply ResNet and FT-Transformer to a new Dataset

### ISSUE THREAD

**Issue by Wajih88** [yandex-research/rtdl#15]
Hi, 
How do we manage to apply those two algorithms for a new (prepared) dataset ?
I saw in the tutorial the tuning needed a toml file ? So how can we make a new one for a new data set ?
Thank you for your help

**Comment by Yura52** [comment]
Hi, I recommend checking this [this reply](https://github.com/yandex-research/rtdl/issues/5#issuecomment-988677723). Does it help?
