### ISSUE TITLE
The results reported in the paper do not match the description and the output files.

### ISSUE THREAD

**Issue by ZhangTP1996** [yandex-research/rtdl#16]
The higgs_small and epsilon datasets are binary classification datasets. According to the paper, the authors should report AUC instead of accuracy. However, I check the output file and find out that the numbers in the paper are accuracy. What is more weird is that, the numbers in the paper for adult (also a binary classification task) match neither accuracy nor AUC! Could anyone please tell me what happens?

**Comment by Yura52** [comment]
We switched to accuracy for binary classification tasks. Please, check the updated version of the paper (Table 1, Page 6): https://arxiv.org/pdf/2106.11959v2.pdf
