### ISSUE TITLE
Normalization techniques comparison

### ISSUE THREAD

**Issue by amirassov** [yandex-research/rtdl#17]
Hello, nice project! 

Have you conducted experiments to compare normalization techniques (e.g. quantile transform vs standard scaler & None & etc.) for DL models? If so, what results have you obtained?

**Comment by Yura52** [comment]
Hello, thanks!

We did not perform a systematic/thorough comparison. I can only say that the chosen normalizations do not "break" the datasets (i.e. they lead to reasonable results).

P.S. I see that you are a Kaggle Grandmaster and I would be glad to learn: what is your default preprocessing strategy when solving tabular data problems? By "default" I mean something that does not involve sophisticated per-feature analysis. Do you use some heuristic rules that allow automatically choosing a reasonable normalization for every feature?

**Comment by amirassov** [comment]
Thanks for answer! 

I can't say something unusual about preprocessing strategy. By default, I use `StandardScaler` and I found it interesting using of `QuantileTransform`.

**Comment by Yura52** [comment]
I see. IMHO, `QuantileTransform` deserves a bit more attention in the context of tabular data problems. Not saying that it is always better than `StandardScaler` (depends on a dataset, as everything else in tabular data 😃 ), but to me personally it is a must-check strategy in addition to `StandardScaler` and "no preprocessing".

P.S. When applying `QuantileTransform`, one may face problems related to low number of unique features. To avoid those, small noise can be added (as it is done [here](https://github.com/yandex-research/rtdl/blob/8cba63363c659e80f2a6e805888a7d104e738ddc/lib/data.py#L33) ).
