### ISSUE TITLE
MLP & Node models always use default cat_policy instead of the policy described in the toml config files

### ISSUE THREAD

**Issue by chengxuanying** [yandex-research/rtdl#2]
MLP & Node models always use default cat_policy instead of the policy described in the toml config files
I think there is a bug here.

https://github.com/yandex-research/rtdl/blob/948ab39101c86e4e198e78cc27776732b4b6d6f7/bin/mlp.py#L82

https://github.com/yandex-research/rtdl/blob/948ab39101c86e4e198e78cc27776732b4b6d6f7/bin/node.py#L91

Reference Code:

https://github.com/yandex-research/rtdl/blob/948ab39101c86e4e198e78cc27776732b4b6d6f7/bin/resnet.py#L121

**Comment by Yura52** [comment]
@chengxuanying thanks for reporting! Since the bug affected only two algorithms on one dataset, we think that it did not affect the overall picture. We chose the simplest way to handle this: we fixed the scripts, removed the two "incorrect" results from `output` and `bin/report.ipynb`.
