### ISSUE TITLE
y = {k: torch.tensor(v, device=device) for k, v in y.items()}

### ISSUE THREAD

**Issue by Mahmedturk** [yandex-research/rtdl#20]
Hi,

I get the following error when i try to run ft- transformer on my binary classification dataset.
ValueError                                Traceback (most recent call last)
<ipython-input-12-6e22e5ae70b2> in <module>()
      1 
      2 
----> 3 y = {k: torch.tensor(v, device=device) for k, v in y.items()}

<ipython-input-12-6e22e5ae70b2> in <dictcomp>(.0)
      1 
      2 
----> 3 y = {k: torch.tensor(v, device=device) for k, v in y.items()}

ValueError: could not determine the shape of object type 'Series'

**Comment by Yura52** [comment]
@Mahmedturk hi! Sorry for the slow reply.

It looks like you are trying to pass objects of the type `pandas.Series` to this line, while numpy-arrays are expected. Try to use the field [values](https://pandas.pydata.org/docs/reference/api/pandas.Series.values.html) to get numpy-arrays. Does this help?

**Comment by Yura52** [comment]
Feel free to reopen the issue if the help is needed!
