### ISSUE TITLE
A scikit-learn interface for RTDL package.

### ISSUE THREAD

**Issue by hengzhe-zhang** [yandex-research/rtdl#30]
Hello! I have written a scikit-learn interface for the RTDL package (https://github.com/hengzhe-zhang/scikit-rtdl). I rely on the skorch to avoid coding errors, and set the default parameters based on the parameters presented in your paper. Hoping you will like it!

**Comment by Yura52** [comment]
Hello! Sorry for the slow reply, and thanks for your work! I like that skorch is used. I should add that hyperparameters for specific models should be tuned, if possible. While we have the default configuration for FT-Transformer, we do not have it for other models (though, good defaults for them may exist as well!).

**Comment by Yura52** [comment]
FYI, the `rtdl` package is now replaced with two packages:
- `rtdl_num_embeddings` ([announcement](https://twitter.com/YuraFiveTwo/status/1737478716685447606), [link](https://github.com/yandex-research/rtdl-num-embeddings/blob/main/package/README.md))
- `rtdl_revisiting_models` ([link](https://github.com/yandex-research/rtdl-revisiting-models/tree/main/package/README.md))

The new packages only implement the papers, so scikit-learn interface is not planned for them. I have been keeping this issue open for quite some time to make it more visible, I hope it helped. Thank you for your repository!
