### ISSUE TITLE
Is it possible to provide a scikit-learn interface?

### ISSUE THREAD

**Issue by zhenlingcn** [yandex-research/rtdl#4]
This project is interesting and I want to use it as the baseline algorithm for my paper. However, it seems that I need to take several steps in order to make a prediction. Consequently, is it possible to provide a scikit-learn interface for making a convenient comparison between different algorithms?

**Comment by Yura52** [comment]
You can try `skorch`, a Scikit-Learn wrapper for PyTorch: https://skorch.readthedocs.io. It looks like exactly what you are looking for. Does it solve your problem?

If you decide to implement things manually, you can take some inspiration from our official example: https://github.com/yandex-research/rtdl/blob/main/examples/rtdl.ipynb

There are other libraries as well, but they do not follow the scikit-learn interface:
- Poutyne (a Keras-like library): https://poutyne.org/index.html
- PyTorch Lightning (a general and powerful library for many kinds of tasks): https://pytorch-lightning.readthedocs.io

**Comment by zhenlingcn** [comment]
Do you mean that I only need to wrap the `FTTransformer` using `skorch`?

**Comment by Yura52** [comment]
**NOTE**: I have updated the previous answer, please, read it first.

> Do you mean that I only need to wrap the `FTTransformer` using `skorch`?

In theory, yes. Note that `rtdl.FTTransformer` expects two arguments (numerical and categorical features), so you will need to read [this section](https://skorch.readthedocs.io/en/latest/user/neuralnet.html#multiple-input-arguments).

**Comment by Yura52** [comment]
Feel free to reopen the issue if you have more questions on the topic.
