### ISSUE TITLE
How to prepare a new dataset for use?

### ISSUE THREAD

**Issue by classopen24** [yandex-research/rtdl#5]
Thanks for sharing this as open source! I am trying to figure out how to convert a new dataset into the format required for the models, and I can't seem to find code for that in the repo. For example, to take a csv file and then convert it into the right files required to input to the model. Could you please help?

**Comment by classopen24** [comment]
Ok, will reopen if I run into any issues. Thanks.

**Comment by Wajih88** [comment]
Hi, 
I was wondering after the dataset preparation , what are the scripts that should be run to get the results ? 
Thanks for your help

**Comment by Yura52** [comment]
Hi! I recommend going through the [tutorial](https://github.com/yandex-research/rtdl#4-tutorial-how-to-reproduce-results) on reproducing results. Compared to the tutorial, the only change that is needed for new datasets is changing the path in tuning config. For example, you if you copy [this config](https://github.com/yandex-research/rtdl/blob/main/output/california_housing/mlp/tuning/0.toml), then you will have to replace `path = 'data/california_housing'` with `path = 'data/<your dataset name>'`.

Note that the parameter space for tuning may need some adjustments for datasets of other "scale" (compared to the ones in this repository) for obtaining the best results.

**Comment by Wajih88** [comment]
thank you for your answer,
If I understand correctly, the config file will take those hyper parameters and along with optuna will try the retrieve the best ones ? (please correctly me if I'm wrong)
Another question if you may : you mentioned in your answer adjustments on "scale". Did you use some rule based or heuristics in this phase ?

**Comment by Yura52** [comment]
> will try the retrieve the best ones ?

Yes, exactly. But you still can launch, say, `bin/mlp.py` with hyperparameters of your choice without tuning.

> adjustments on "scale"

I mean that if your dataset size is significantly different from the ones in the repository (for example, it contains only hundreds of objects, or, the opposite, hundreds of millions of objects), then you may need to adjust the config. Otherwise, you can just copy the config for the dataset that is most similar to your dataset and use it as is.

**Comment by g1644222** [comment]
Hello.
I have a problem with Yahoo and microsoft dataset.

It is how to use q_train/test/val.npy.
I have checked the program and there is no indication that q_train/test/val.npy is being used.
How are you using it?

**Comment by Yura52** [comment]
Hello. 

The `q_<...>.npy` arrays contain query identifiers for the original ranking problems. In our project, we treat ranking problems as regression problems, so the identifiers are not used. Note that the identifiers in train, validation and test parts do NOT intersect and this is a strict requirement for new ranking datasets as well. For example:

```
In [15]: import numpy as np

In [16]: a = np.load('data/microsoft/q_train.npy')

In [17]: b = np.load('data/microsoft/q_val.npy')

In [18]: c = np.load('data/microsoft/q_test.npy')

In [19]: set(a) & set(b)
Out[19]: set()

In [20]: set(a) & set(c)
Out[20]: set()

In [21]: set(b) & set(c)
Out[21]: set()
```

**Comment by g1644222** [comment]
Thank you very much for your answer.
Does this mean that the q_train/test/val.npy data will not be loaded during training?
Also, is there anything else I should be aware of when creating the data?

**Comment by Yura52** [comment]
> Does this mean that the q_train/test/val.npy data will not be loaded during training?

Yes, this is correct.

> Also, is there anything else I should be aware of when creating the data?

It should be enough to follow the format of other datasets (including data types). [This comment](https://github.com/yandex-research/rtdl/issues/5#issuecomment-934757481) can be helpful. Feel free to ask questions in case of any problems.
