### ISSUE TITLE
About piecewise_linear_encoding

### ISSUE THREAD

**Issue by Minhvt34** [yandex-research/rtdl#57]
Hi Yura!

I have run the test code, which is mentioned in your code `data.piecewise_linear_encoding`
I have this error: RuntimeError: The size of tensor a (4) must match the size of tensor b (100) at non-singleton dimension 1

this error causes by `is_last_bin = bin_indices + 1 == as_tensor(list(map(len, bin_edges)))`

while `bin_indices + 1` is a `torch.Size([100, 4])`, and `as_tensor(list(map(len, bin_edges)))` returns a `torch.Size([100])`

**Comment by Yura52** [comment]
Hi! Are you referring to [this code snippet](https://github.com/Yura52/rtdl/blob/60ae9814585d9792e112608a27e2bbbbdcbd3388/rtdl/data.py#L579)?

**Comment by Minhvt34** [comment]
> Hi! Are you referring to [this code snippet](https://github.com/Yura52/rtdl/blob/60ae9814585d9792e112608a27e2bbbbdcbd3388/rtdl/data.py#L579)?

yes, I am trying to use piecewise linear encoding but there is an error as above.

**Comment by Yura52** [comment]
Hi @Minhvt34 ! Sorry for such a long pause. There is now a new package that correctly implements piecewise-linear encoding and other embeddings:
- [The package](https://github.com/yandex-research/rtdl-num-embeddings/tree/main/package#python-package-)
- [The announcement](https://twitter.com/YuraFiveTwo/status/1737478716685447606) with more details

**Comment by Minhvt34** [comment]
> Hi @Minhvt34 ! Sorry for such a long pause. There is now a new package that correctly implements piecewise-linear encoding and other embeddings:
> 
> * [The package](https://github.com/yandex-research/rtdl-num-embeddings/tree/main/package#python-package-)
> * [The announcement](https://twitter.com/YuraFiveTwo/status/1737478716685447606) with more details

Awesome! I am glad that you are still working on the project. I found your method works pretty well! Keep doing such a greate work.
