### ISSUE TITLE
怎么运行？

### ISSUE THREAD

**Issue by Cgetier520990** [yandex-research/rtdl#64]
你好，请问这个代码怎么运行？代码好像只提供了模型，没有提供数据。换句话说，这个代码怎么调用表格数据，如果我想给表格的数据分类，我应该怎么做？

**Comment by Yura52** [comment]
Sorry for the slow reply, is the help still needed?

**Comment by Cgetier520990** [comment]
Thank you for your reply. Well, I still need your help. I can't run your project mainly because there is a lack of training functions. My data set is in CSV format, which contains both text data and numerical data. I want to train with my own data and then do the verification. What should I do?

**Comment by Yura52** [comment]
This project only provides [a list of papers](https://github.com/yandex-research/rtdl?tab=readme-ov-file#papers). Some of the papers have their own Python packages that provide PyTorch modules and end-to-end examples showing how to train them ([example](https://github.com/yandex-research/rtdl-num-embeddings/blob/main/package/example.ipynb)). However, there are no high-level training functions in those packages.

Also, there is [Skorch](https://github.com/skorch-dev/skorch) -- a package that provides a Scikit-learn wrapper for any PyTorch module, so you can take one of our models and pass it to the wrapper. Though you should not rely on the default hyperparameters in that package, they can be far from optimal.

Does this help?

P.S. The package `rtdl` is deprecated, so individual packages of the aforementioned papers should be used instead.

**Comment by Cgetier520990** [comment]
yeah，I maybe get it, thank you very much.

**Comment by Yura52** [comment]
Feel free to reopen the issue if further help is needed
